### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by justinccdev** [buzzbangorg/bsbang-frontend#1]
Need some kind of logo (I'm a programmer, not an artist, Jim :)

**Comment by KukkadapuSushma** [comment]
Can you give little more briefing on how the logo should be - like related to?? @justinccdev

**Comment by justinccdev** [comment]
Buzzbang search is going to be quite general. initially bio and things like DataCatalogs, Datasets, Samples, BioChemEntities, and only to find these things, not to do any sophisticated query.  Eventually it may also encompass research data in general.

So something clean and simple, I think, and not bio-specific. Maybe some iconography combining science and data, or maybe just text (again, I'm thinking Google-like, where their original logo was very simple).

**Comment by KukkadapuSushma** [comment]
Sure. Thanks for the inputs. Will update you, with my thoughts! @justinccdev  :)

**Comment by ggcarlosr** [comment]
Good morning Sr. the logo requirement still stands ?

**Comment by justinccdev** [comment]
I did create this simple logo recently that I like a lot and am using at buzzbang.science.  However, if you can think of something better in the same minimalist style, I'd be very interested to see it!

![image](https://user-images.githubusercontent.com/12761716/38323057-18c209a2-3834-11e8-9f0b-063b6f4b312d.png)

**Comment by ggcarlosr** [comment]
perfect in the coming days this presentation presenting a proposal according to what you want. I hope to pass the challenge ;)

**Comment by ggcarlosr** [comment]
Good morning here a small proposal subject to changes, which minimizes what you want in a letter and with a very simple typography too

![bussbang](https://user-images.githubusercontent.com/37964430/38623076-be57db42-3d72-11e8-8764-2d83dff204b0.png)

**Comment by justinccdev** [comment]
Hey @ggcarlosr.  This looks really nice.  I wonder, do you think it might be possible to make the top b look like a magnifying glass in any way?  This would emphasize that buzzbang is about finding science data.  I know there's no hint of this in the current logo but that's because I slapped it together from stock elements really quickly. And I appreciate it may be tough since b's (and beakers!) don't look like much like magnifying glasses :)

**Comment by ggcarlosr** [comment]
Hey, thank you for your appreciation and I think your suggestion is excellent, I will adapt what you indicate keeping the current to lose the theme with respect to the scientific.

**Comment by ggcarlosr** [comment]
hey brother try to keep some elements and I put aside the letter "b" thought more to the iconic search engine and attach the magnifying glass as you requested. Would you believe that something else is missing?

![bussbang](https://user-images.githubusercontent.com/37964430/38696842-5071c65a-3e5e-11e8-90b0-d6800ee66fef.png)

**Comment by ggcarlosr** [comment]
hey brother try to keep some elements and I put aside the letter "b" thought more to the iconic search engine and attach the magnifying glass as you requested. Would you believe that something else is missing? 

![bussbang](https://user-images.githubusercontent.com/37964430/38697176-4229e4d2-3e5f-11e8-8cbc-c2357d809969.png)

**Comment by justinccdev** [comment]
Hey @ggcarlosr, I really like this and would love to add it to the project.  Would you be willing to license these logos under https://creativecommons.org/licenses/by/4.0/ ?

**Comment by ggcarlosr** [comment]
Hey, thank you for your approval, of course I will grant the respective licenses so you can add it to your project. Thanks for your approval. then I will be delivering the editable files to be added to the project.

**Comment by justinccdev** [comment]
Thanks a lot @ggcarlosr, that's really great.  I'm busy now for maybe a couple of weeks but I or someone else will incorporate the new logo soon.

**Comment by justinccdev** [comment]
@ggcarlosr As you can see from http://www.buzzbang.science/, I finally got around to switching in your logo.  Sorry for the delay.  Thanks again!
